[2025-09-13T04:28:04.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T04:28:04.249+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_seismic_qa.qa_chequeos manual__2025-09-13T04:28:03.037584+00:00 [queued]>
[2025-09-13T04:28:04.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_seismic_qa.qa_chequeos manual__2025-09-13T04:28:03.037584+00:00 [queued]>
[2025-09-13T04:28:04.262+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-13T04:28:04.298+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): qa_chequeos> on 2025-09-13 04:28:03.037584+00:00
[2025-09-13T04:28:04.316+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_seismic_qa', 'qa_chequeos', 'manual__2025-09-13T04:28:03.037584+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_seismic_qa.py', '--cfg-path', '/tmp/tmpu34hrdcu']
[2025-09-13T04:28:04.321+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=290) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-13T04:28:04.323+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask qa_chequeos
[2025-09-13T04:28:04.324+0000] {standard_task_runner.py:63} INFO - Started process 292 to run task
[2025-09-13T04:28:04.403+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_seismic_qa.qa_chequeos manual__2025-09-13T04:28:03.037584+00:00 [running]> on host 4044a091ce26
[2025-09-13T04:28:04.493+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_seismic_qa' AIRFLOW_CTX_TASK_ID='qa_chequeos' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T04:28:03.037584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T04:28:03.037584+00:00'
[2025-09-13T04:28:04.494+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T04:28:04.506+0000] {logging_mixin.py:188} INFO - QA seismic_events: nulls/rangos OK.
[2025-09-13T04:28:04.506+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-13T04:28:04.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T04:28:04.513+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_seismic_qa, task_id=qa_chequeos, run_id=manual__2025-09-13T04:28:03.037584+00:00, execution_date=20250913T042803, start_date=20250913T042804, end_date=20250913T042804
[2025-09-13T04:28:04.555+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-13T04:28:04.578+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T04:28:04.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
